// AI vocabulary → human replacement table
// Sorted by descending phrase length to avoid partial matches.
// Each entry: [aiPhrase, humanReplacement]
// Replacement of "" means delete the phrase.

export const vocabReplacements: [string, string][] = [
  // Multi-word phrases (longest first)
  ["it could be argued that it might", "it may"],
  ["while specific details are limited in available sources", ""],
  ["marking a pivotal moment in the evolution of", ""],
  ["this represents a major step in the right direction", ""],
  ["would you like me to expand on any section", ""],
  ["seems to potentially suggest", "suggests"],
  ["could potentially possibly", "might"],
  ["stands as a testament", "proves"],
  ["serves as a testament", "proves"],
  ["let me know if you have any questions", ""],
  ["as of my knowledge cutoff", ""],
  ["based on available information", ""],
  ["it is important to note that", ""],
  ["it is worth noting that", ""],
  ["it goes without saying that", ""],
  ["in a controlled manner", "carefully"],
  ["due to the fact that", "because"],
  ["at this point in time", "now"],
  ["journey toward excellence", ""],
  ["exciting times lie ahead", ""],
  ["the future looks bright", ""],
  ["as we look to the future", ""],
  ["has the ability to", "can"],
  ["evolving landscape of", ""],
  ["reflects broader trends", ""],
  ["setting the stage for", "leading to"],
  ["here is an overview of", ""],
  ["here is a summary of", ""],
  ["you're absolutely right", ""],
  ["deeply rooted in", "based in"],
  ["in the event that", "if"],
  ["state-of-the-art", "modern"],
  ["i hope this helps", ""],
  ["feel free to ask", ""],
  ["in the heart of", "in"],
  ["key turning point", "turning point"],
  ["right direction", ""],
  ["that being said", "still"],
  ["on top of that", "also"],
  ["paradigm shift", "big change"],
  ["indelible mark", "lasting impact"],
  ["great question", ""],
  ["cutting-edge", "modern"],
  ["needless to say", ""],
  ["in order to", "to"],
  ["in conclusion", ""],
  ["to summarize", ""],
  ["touch base", "check in"],
  ["circle back", "follow up"],
  ["deep dive", "close look"],
  ["delve into", "dig into"],
  ["embark on", "start"],
  ["nestled in", "in"],
  ["align with", "match"],
  ["stands as", "is"],
  ["serves as", "is"],
  ["functions as", "is"],
  ["prior to", "before"],
  ["acts as", "is"],
  ["marks a", "is a"],
  ["represents a", "is a"],
  ["testament to", "proof of"],
  ["at its core", ""],
  ["certainly!", ""],
  ["of course!", ""],
  // Single words / short phrases — formal/procedural vocabulary
  ["furthermore", "on top of that"],
  ["consequently", "so"],
  ["subsequently", "then"],
  ["additionally", ""],
  ["nonetheless", "still"],
  ["nevertheless", "even so"],
  ["immediately", "right away"],
  ["moreover", "also"],
  ["essentially", ""],
  ["explicitly", ""],
  ["unprecedented", "unusual"],
  ["transformative", "significant"],
  ["comprehensive", "thorough"],
  ["groundbreaking", "new"],
  ["significantly", ""],
  ["breathtaking", "impressive"],
  ["intricacies", "details"],
  ["emphasizing", "showing"],
  ["showcasing", "showing"],
  ["streamline", "simplify"],
  ["innovative", "new"],
  ["interplay", "relationship"],
  ["showcases", "shows"],
  ["holistic", "broad"],
  ["intricate", "complex"],
  ["fostering", "building"],
  ["leveraging", "using"],
  ["spearhead", "lead"],
  ["underscores", "shows"],
  ["underscore", "show"],
  ["highlights", "shows"],
  ["renowned", "well-known"],
  ["stunning", "impressive"],
  ["leverage", "use"],
  ["tapestry", "mix"],
  ["catalyst", "driver"],
  ["showcase", "show"],
  ["commence", "start"],
  ["endeavour", "try"],
  ["endeavor", "try"],
  ["ascertain", "find out"],
  ["designated", "set"],
  ["personnel", "people"],
  ["mechanism", "system"],
  ["apparatus", "device"],
  ["procedure", "process"],
  ["anomalies", "problems"],
  ["disengage", "release"],
  ["terminate", "end"],
  ["following", "after"],
  ["initiate", "start"],
  ["activate", "turn on"],
  ["inspects", "checks"],
  ["resolves", "fixes"],
  ["utilize", "use"],
  ["utilise", "use"],
  ["seamless", "smooth"],
  ["synergy", "collaboration"],
  ["fosters", "builds"],
  ["crucial", "important"],
  ["pivotal", "key"],
  ["vibrant", "active"],
  ["elevate", "improve"],
  ["execute", "do"],
  ["robust", "solid"],
  ["verify", "check"],
  ["ensure", "make sure"],
  ["embark", "start"],
  ["garner", "get"],
  ["boasts", "has"],
  ["delve", "explore"],
  ["realm", "field"],
  ["nuance", "detail"],
];
